name: Cleanup Mirrored Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-mirrored-branch:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Use GitHub's REST API to delete the mirrored branch
      - name: Delete Mirrored Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract branch and repository details
          MIRRORED_BRANCH="pr-${{ github.event.pull_request.number }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"

          # Call GitHub's REST API to delete the branch
          curl -X DELETE \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$OWNER/$REPO/git/refs/heads/$MIRRORED_BRANCH"
