name: Mirror Forked PR for Preview

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  mirror-branch:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create mirrored branch
      - name: Fetch and Create Mirrored Branch
        run: |
          # Fetch the pull request directly using its ID
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
          # Checkout the mirrored branch
          git checkout pr-${{ github.event.pull_request.number }}
          # Push the mirrored branch to the repository
          git push origin pr-${{ github.event.pull_request.number }}


      # Step 4: Post "Deployment in Progress" comment on PR
      - name: Post Deployment In Progress Comment
        id: post_comment
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `🔄 Deployment is in progress for branch \`pr-${{github.event.pull_request.number}}\`... You will be able to view your branch's deployment here: https://pr-${{github.event.pull_request.number}}.elys-learn.pages.dev/`;
            const { data } = await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
            core.setOutput("comment_id", data.id);
