name: Mirror Forked PR for Preview

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  mirror-branch:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create mirrored branch
      - name: Fetch and Create Mirrored Branch
        run: |
          # Fetch the pull request directly using its ID
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
          # Checkout the mirrored branch
          git checkout pr-${{ github.event.pull_request.number }}
          # Push the mirrored branch to the repository
          git push origin pr-${{ github.event.pull_request.number }}

      # Step 3: Add a delay to allow Cloudflare Pages build to initialize
      - name: Wait for Cloudflare Build to Start
        run: sleep 10 # Wait for 10 seconds (adjust as needed)

      # Step 4: Post "Deployment in Progress" comment on PR
      - name: Post Deployment In Progress Comment
        id: post_comment
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `🔄 Deployment is in progress for branch \`pr-${{ github.event.pull_request.number }}\`... Please wait for the preview link.`;
            const { data } = await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
            core.setOutput("comment_id", data.id);

      # Step 5: Wait for Cloudflare Deployment and Fetch Preview URL with Retry Logic
      - name: Wait for Cloudflare Deployment and Fetch Preview URL
        id: fetch_preview_url
        uses: zentered/cloudflare-preview-url@v1.4.2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          cloudflare_project_id: elys-learn
          branch: pr-${{ github.event.pull_request.number }}
          wait_until_ready: true

      # Step 6: Update PR comment with Preview URL
      - name: Update Comment with Preview URL
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const url = `https://${{ steps.fetch_preview_url.outputs.preview_url }}`;
            const updatedComment = `🚀 **Cloudflare Pages Preview:** [View Deployment](${url})`;
            github.rest.issues.updateComment({
              comment_id: ${{ steps.post_comment.outputs.comment_id }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: updatedComment,
            });

      # Step 7 (Optional): Handle Timeout or Failure Gracefully
      - name: Handle Timeout or Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const updatedComment = `❌ **Deployment Failed:** Unable to fetch preview URL. Please check the Cloudflare Pages dashboard for details.`;
            github.rest.issues.updateComment({
              comment_id: ${{ steps.post_comment.outputs.comment_id }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: updatedComment,
            });
